### ISSUE TITLE
Error Getting cluster

### ISSUE THREAD

**Issue by stuartleeks** [xinsnake/databricks-sdk-golang#2]
When I attempt to connect to Azure Databricks and retrieve a cluster I get the error `Error getting: unexpected end of JSON input`

Looking into this a bit further, the cluster json that comes back from the API is 

```json
{
  "cluster_id": "1011-000000-verge721",
  "spark_context_id": 000000000000,
  "num_workers": 10,
  ... // some lines removed for brevity
  "default_tags": {
    "Vendor": "Databricks",
    "Creator": "stuartle@microsoft.com",
    "ClusterName": "job-2-run-2",
    "ClusterId": "1011-151038-verge721"
  },
  "creator_user_name": "stuartle@microsoft.com",
  "termination_reason": {
    "code": "JOB_FINISHED"
  },
  "init_scripts_safe_mode": false
}
```

Here the `default_tags` property is a dictionary but the property on the model is `[]modes.ClusterTag`. 

Attempting to list clusters gives this error instead which also points to this being the issue: `Error listing: json: cannot unmarshal object into Go struct field ClusterInfo.default_tags of type []models.ClusterTag`

Looking at the code for `ClustersAPI.Get` the error returned on [this line](https://github.com/xinsnake/databricks-sdk-golang/blob/master/azure/clusters.go#L110) isn't checked which probably accounts for the difference in error messages

**Comment by storey247** [comment]
Have raised a PR that should fix the model ☝️ can someone review please?
